<?xml version='1.0'?>

<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<link name="robot_footprint"></link>

  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="robot_footprint"/>
    <child link="chassis" />
  </joint>

  <link name='chassis'>
    <pose>0 0 0.1 0 0 0</pose>

    <inertial>
      <mass value="15.0"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <collision name='collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/> 
      <geometry>
        <!--<box size="${chassis_box_x} ${chassis_box_y} ${chassis_box_z}"/>-->
        <cylinder radius="${chassis_r}" length="${chassis_h}"/>
      </geometry>
    </collision>

    <visual name='chassis_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <!--<box size="${chassis_box_x} ${chassis_box_y} ${chassis_box_z}"/>-->
        <cylinder radius="${chassis_r}" length="${chassis_h}"/>
      </geometry>
    </visual>


    <collision name='back_caster_collision'>
      <origin xyz="${-chassis_r+0.05} 0 ${-chassis_h/2}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius-chassis_h/2}"/>
      </geometry>
    </collision>

    <visual name='back_caster_visual'>
      <origin xyz="${-chassis_r+0.05} 0 ${-chassis_h/2}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius-chassis_h/2}"/>
      </geometry>
    </visual>

    <collision name='front_caster_collision'>
      <origin xyz="${+chassis_r-0.05} 0 ${-chassis_h/2}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius-chassis_h/2}"/>
      </geometry>
    </collision>

    <visual name='front_caster_visual'>
      <origin xyz="${+chassis_r-0.05} 0 ${-chassis_h/2}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius-chassis_h/2}"/>
      </geometry>
    </visual>

  </link>

  </robot>